version: '3.8'

services:
  persons.api:
    build:
        context: ./Person.API
        dockerfile: Dockerfile
    image: person-service-image 
    container_name: person-service
    ports:
      - "5000:80" 
    depends_on:
      - mongodb

  report.api:
    build:
        context: ./Report.API
        dockerfile: Dockerfile
    image: report-service-image 
    container_name: report-service
    ports:
      - "5001:80"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672" 
      - "5672:5672"   